### ISSUE TITLE
Adding custom logic, validation etc.

### ISSUE THREAD

**Issue by lyndoh** [awslabs/fhir-works-on-aws-routing#46]
Hi,

Firstly, thanks so much for this project! Hoping I can get some advice on some custom logic scenarios.

We have some requirements that require some customization of the logic within the routing package (I think) and trying to work out how to do this. To give some examples:

- Only allow one user to retrieve/view a resource at a time (only for certain types). Once a user "GET"s a resource that resource cannot be "GET" by any other user until the first user releases it or a timeout expires.
- Support a different schema/profile (australian base profile +)
- Validating that a resource referenced from a created resource contains certain data

Hope those cases make sense.

My thoughts for customising the logic we require include:
- Extending the ResourceHandler class (CrudHandlerInterface)
- Replacing the Validator class to add different schema
- Replacement of GenericResourceRoute if there are instances where access to the express request/response is required?
- Replace the generateServerlessRouter(), allows adding express middleware, customising the resourcehandler type etc.

Am I on the right track do you think? 
How can I customize these without either replacing this entire package with my own version, or monkey patching this package? I guess writing our own version of generateServerlessRouter() would allow us to customize all this without modifying the package, but might add a headache of trying to keep the non-custom parts of the function in sync with the one in the package etc.

If it's not possible currently, are you open to PR's that allow, for example, passing a custom CrudHandlerInterface  implementation via the FhirConfig?

Thanks for your help

**Comment by rsmayda** [comment]
Glad to hear your enjoying the project so far!

- Only allow one user to retrieve/view a resource at a time (only for certain types). Once a user "GET"s a resource that resource cannot be "GET" by any other user until the first user releases it or a timeout expires.
  - Very interesting use-case I haven't thought much about this - but you will probably need to add this locking logic to the `persistence` layer.
  - As for locking out [specific ResourceTypes](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L21) or [operations](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L83) you can control those two things in the fhirConfig
- Support a different schema/profile (australian base profile +)
  - We are working on IGs/Profiles support now 
- Validating that a resource referenced from a created resource contains certain data
  - This sounds like [referential integrity](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/19)? Or is this more than that?

As for the best path forward I think a good bit of the work would be done in the `persistence` layer, with maybe smaller updates to the `router`. For the `router` optimally the changes are generic enough to bring into mainline via PR. On the `persistence` side you may need to roll your own package due to this specific locking use-case.

I hope this helps! Happy to chat more

Robert

**Comment by lyndoh** [comment]
Thanks for the response.

I had a look at adding the locking logic to the persistence layer, however the persistence layer isn't currently passed the userIdentity which would be required. Would modifying things to pass the userIdentity into the persistence layer seem reasonable to you?

I'm actually starting to wonder if some of our use cases like the locking would best/easiest be handled in the lambda handler before/after calling into the fhir-works-on-aws express pipeline rather than being able to customize the internal behaviour of the fhir server itself... treat the fhir server as a separate service that we layer our business logic over... 

Looking forward to seeing what you are doing with IGs as we are just starting to investigate that at the moment!

Thanks

**Comment by rsmayda** [comment]
> Would modifying things to pass the userIdentity into the persistence layer seem reasonable to you?

Hmmm yeah I think you would have to pass that in as well (which may require an interface change). Especially since you want to add this locking on 'GET's

The idea of treating the FHIR server as a black box and you intercept it before/after is a strong idea. You could do it before and use the user's access_token as their ID to lock against.
