### ISSUE TITLE
Support for PATCH

### ISSUE THREAD

**Issue by lyndoh** [awslabs/fhir-works-on-aws-routing#62]
Hi,

We are looking at using PATCH functionality in our api and notice it's not fully supported in fhir-works yet. We have some idea's on how to implement this in fhir-works and will create a PR if you're happy with the solution.

First I note there is also an outstanding issue to add patch support in persistence-ddb awslabs/fhir-works-on-aws-persistence-ddb#6 

Our idea is to add the patch functionality to the ResourceHandler. The patch function would become something like:

```
async patch(resourceType: string, id: string, resource: any) {
  const currentResource= await this.dataService.readResource({ resourceType, id });
  const patchedResource = jsonPatch.applyPatch(currentResponse.resource, resource).newDocument;
  
  return await update(resourceType, id, patchedResource);
}
```

Calling the existing update() function to update the resource ensures the validation rules are applied and should satisfy the fhir docs on patch 

> the server SHALL process its own copy of the resource in the format indicated, applying the operations specified in the document, following the relevant PATCH specification. When the operations have all been processed, the server processes the resulting document as an Update operation; all the version and error handling etc. apply as specified

If performing the patch in the persistence layer as per the above issue it would be more difficult to process validation etc. we think our solution above would be a better fit.

This would probably also result in the removal of patchResource() from the persistence interface as it would no longer be required, so this change may not be backward compatible.

Some changes would also be required in GenericResourceRoute for patch() where it performs some checks on the 'id' field in the body, which won't exist (at least not in a JSON patch spec document) so we'd fix this too, probably just replace it with a basic check that the body is an array.

What do you think?

**Comment by rsmayda** [comment]
Thank you so much for a thoughtful response. Let us review this in depth, since like you mention it will be a backward breaking change. At face value this looks like a good logical approach but we will get back to you soon.

Just for our planning do you guys have a deadline?

**Comment by lyndoh** [comment]
Thanks, deadline is not too soon.

**Comment by rsmayda** [comment]
Hey @lyndoh after further review, I have no modifications or qualms with this approach. This makes a great deal of sense and we would support this sort of PR. As you mentioned this would be a backwards breaking change so I believe the order of operations would be:

1. Update interface (bumping major version) - removing the interface method
    * Please add comments explaining that due to the FHIR spec is makes more sense for this to be a  contained within the router
2. Update persistence (bumping major version) - removing the method
3. Update routing (bumping minor version - since the patch route would still be support but just in a different way)
4. Update deployment package - (do we need to do anything to support a new header? `application/json-patch+json`)

For steps on setting up your local environment please check out our: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/DEVELOPMENT.md

Since all of these PRs will be linked so heavily we will not merge the interface PR (and subsequently bump the npm version) until we are able to see the other changes code.

We look forward to this awesome contribution!

**Comment by lyndoh** [comment]
Thanks that all sounds good. We'll look to get started on this soon.

**Comment by kcadette** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com](mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake](https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
